use_frameworks!

platform :ios, '8.0'

target 'LWPurchase_Example' do
  pod 'LWPurchase', :path => '../'

  pod 'SDWebImage', '~> 5.0.1'

  pod 'FCAlertView', '~> 1.4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry'

  # target 'LWPurchase_Tests' do
  #   inherit! :search_paths
  #
  # end
end
