source 'https://gitlab.com/ioslibraries1/mygitlabrepo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'LWPurchase_Example' do
  pod 'LWPurchase', :path => '../'

  pod 'FCAlertView', '~> 1.4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry'
  pod 'Reachability'
  
  pod 'LWSDWebImage',:source => 'https://gitee.com/lw_ios_project/mylibrepo.git'
  pod 'LWHUD',:source => 'https://gitee.com/lw_ios_project/mylibrepo.git'

  # target 'LWPurchase_Tests' do
  #   inherit! :search_paths
  #
  # end
end
